in ../../Tool/citp

in nslpk.maude

select #CITP# .

loop init .

---> Lemma:
(goal NSLPK |-
  ceq intr \in N1:Nonce = true
   if (N1:Nonce \in nonces(S:Sys)) = true ;
  ceq prop(intr, N1:Nonce, S:Sys) = true
   if (enc1(Q1:Prin,N1:Nonce,intr) \in nw(S:Sys)) = true [nonexec] ;
  ceq prop(intr, N2:Nonce, S:Sys) = true
   if (enc2(Q1:Prin,N1:Nonce,N2:Nonce,intr) \in nw(S:Sys)) = true [nonexec] ;)


(ind on S:Sys red ca red tc red imp red)