***( REPL/Examples

  This file is part of the REPL-examples suite.

  Copyright : (C) 2020, 2021 Simion Stoilow Institute of Mathematics
              of the Romanian Academy (IMAR)
  License   : GNU General Public License v2.0 or later (GPL-2.0-or-later)
  Author    : Ionut Tutu <Ionut.Tutu@imar.ro>

)

sload ./Echo.maude

********************************************************************************

mod ECHO-FILES-INTERPRETER is
  including  BASIC-INTERPRETER { NIndex{Snippet/IO/String}, Echo } .
  protecting EXT-BOOL .

  var O : Oid .
  var S : String .
  var QIL : QidList .
  var Atts : AttributeSet .

  *** objects  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  op Echo : -> Oid [ctor] .

  *** rules  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  crl < Echo : INT | running, Atts >
    eval(Echo, O, S)
   => < Echo : INT | running, Atts >
     if QIL :: NeQidList and-then head(QIL) == 'load
     then visit-file(O, printTokens(tail(QIL)))
     else print(O, emph(trim(S))) fi
   if QIL := tokenize(S) .
endm

********************************************************************************

*** erew in ECHO-FILES-INTERPRETER : start Echo .
*** quit
