in leq
fmod FG is
 pr LEQ .
 op _+_ : Nat Nat -> Nat [assoc comm].
 op _<=_ : Nat Nat -> Bool[metadata "transitive"].
 op F : Nat -> Nat .
 op G : Nat -> Nat .
 vars X Y Z : Nat .
---
 eq X + 0 = X .
 eq X + (s Y) = s (X + Y) .
---
 ceq F(X) = s_^5(0) if X <= s_^7(0) [metadata "CA:F1"].
 ceq F(X) = s 0   if s_^8(0) <= X [metadata "CA:F2"].
---
 ceq G(Y) = s_^2(0) if Y <= s_^4(0)[metadata "CA:G1"].
 ceq G(Y) = s_^7(0) if s_^5(0) <= Y [metadata "CA:G2"]. 
endfm
