***( SpeX/Lang/Base/Common

  This file is part of the SpeX-languages suite.

  Copyright : (C) 2021 Simion Stoilow Institute of Mathematics of the
              Romanian Academy (IMAR)
  License   : GNU General Public License v2.0 or later (GPL-2.0-or-later)
  Author    : Ionut Tutu <Ionut.Tutu@imar.ro>

)

sload ../../../CommonLibs/QidSet.maude

********************************************************************************

fmod PROP-SET-DECL is
  protecting QID-SET/OPS .

  var QIS : QidSet .

  *** PropSetDecl  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  sort PropSetDecl .
  op (props_.) : QidSet -> PropSetDecl [ctor format (d s s d)] .

  *** list  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - --
  op list : PropSetDecl -> QidList .
  eq list(props QIS .) = list(QIS) .
endfm

********************************************************************************
