***( CITP

  This file is part of CITP.

  License : GNU General Public License v2.0 or later (GPL-2.0-or-later)
  Authors : Daniel Gaina <daniel@imi.kyushu-u.ac.jp>,
            Ionut Tutu <Ionut.Tutu@imar.ro>,
            Adrian Riesco <ariesco@fdi.ucm.es>

)

sload ./Core.maude
sload ./Lang/CITP/Processor.maude

********************************************************************************

view CITP/Preset from SPEX/PRESET to SPEX/LANG { CITP } is
  op preset to term lang(CITP) .
endv

*** ----------------------------------------------------------------------------

view CITP/UI from INTERPRETER/UI to STRING/FORMATTING + PROMPT is
  op banner to term
    "\n\033[1m"
    + "  Welcome to\n"
    + "    \033[36m_ \033[35m_        \n"
    + " \033[32m__\033[36m(_) \033[35m|_ \033[31m_ __ \n"
    + "\033[32m/ _\033[36m| |  \033[35m_\033[31m| '_ \\\n"
    + "\033[32m\\__\033[36m|_|\033[35m\\__\033[31m| .__/\n"
    + "         \033[31m|_|   \n\n\033[0m" .
  op prompt to term ["CITP" >] .
  op goodbye to term "\n\033[1mGoodbye\033[0m\n\n" .
endv

*** ----------------------------------------------------------------------------

mod CITP/INTERPRETER is
  including SPEX/CORE { CITP/Preset, CITP/UI } *
    (op SpeX : -> Oid to citp) .
  including CITP/PROCESSOR .
endm

********************************************************************************
