***( SpeX

  This file is part of SpeX, a simple framework for working with
  formal specifications based on SAP and REPL.

  Copyright : (C) 2021, 2022 Simion Stoilow Institute of Mathematics
              of the Romanian Academy (IMAR)
  License   : GNU General Public License v2.0 or later (GPL-2.0-or-later)
  Author    : Ionut Tutu <Ionut.Tutu@imar.ro>

)

sload ./CommonLibs/Formatting.maude

********************************************************************************

fmod SPEX/FORMATTING is
  protecting QID-LIST/FORMATTING .

  *** advisories & warnings  - - - - - - - - - - - - - - - - - - - - - - - - - -
  op Advisory: : -> QidList .
  eq Advisory: = '\g '\! 'Advisory: '\o .

  op Warning: : -> QidList .
  eq Warning: = alert('Warning:) .
endfm

********************************************************************************
