***( SpeX

  This file is part of SpeX, a simple framework for working with
  formal specifications based on SAP and REPL.

  Copyright : (C) 2021, 2022 Simion Stoilow Institute of Mathematics
              of the Romanian Academy (IMAR)
  License   : GNU General Public License v2.0 or later (GPL-2.0-or-later)
  Author    : Ionut Tutu <Ionut.Tutu@imar.ro>

)

*** sload ./Lang/Spec/Processors.maude
sload ./Lang/CITP/Processor.maude

********************************************************************************

mod SPEX/KNOWLEDGE-BASE is
  *** including SPEC/PROCESSORS .
  including CITP/PROCESSOR .
endm

********************************************************************************
