***( SpeX

  This file is part of SpeX, a simple framework for working with
  formal specifications based on SAP and REPL.

  Copyright : (C) 2021, 2022 Simion Stoilow Institute of Mathematics
              of the Romanian Academy (IMAR)
  License   : GNU General Public License v2.0 or later (GPL-2.0-or-later)
  Author    : Ionut Tutu <Ionut.Tutu@imar.ro>

)

sload ./SAP/SAP.maude
sload ./SAP/Compat.maude

********************************************************************************

fmod SPEX/LANG/BASE is
  protecting QID-LIST .

  var QIL : QidList .

  *** SpeX/Lang  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  sort SpeX/Lang .
  op none : -> [SpeX/Lang] [ctor] .

  *** decode-lang (loosely defined)  - - - - - - - - - - - - - - - - - - - - - -
  op decode-lang : QidList ~> SpeX/Lang .

  *** print  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  op print : SpeX/Lang -> QidList .

  *** string  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - --
  op string : SpeX/Lang -> String .

  *** is known-lang  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  op _is`known-lang : QidList -> Bool .
  eq QIL is known-lang = decode-lang(QIL) :: SpeX/Lang .
endfm

*** ----------------------------------------------------------------------------

fmod SPEX/LANG { L :: LANGUAGE } is
  including  SPEX/LANG/BASE .
  protecting LANG-NAME { L } .

  var L : L$Lid .
  var QIL : QidList .

  *** lang  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - --
  op lang : L$Lid -> SpeX/Lang [ctor] .

  *** decode-lang-name  - - - - - - - - - - - - - - - - - - - - - - - - - - - --
  ceq decode-lang(QIL) = lang(Lid) if QIL = name(Lid) .

  *** print  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  eq print(lang(L)) = name(L) .

  *** string  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - --
  eq string(lang(L)) = printTokens(name(L)) .
endfm

********************************************************************************
