***( SpeX/CommonLibs

  This file is part of CommonLibs (CL), a suite of Maude 3 libraries
  that extend the predefined data modules from the standard prelude.

  Copyright : (C) 2022 Simion Stoilow Institute of Mathematics of the
              Romanian Academy (IMAR)
  License   : GNU General Public License v2.0 or later (GPL-2.0-or-later)
  Author    : Ionut Tutu <Ionut.Tutu@imar.ro>

)

********************************************************************************

fmod STRING-LIST is
  protecting LIST { String } *
    (sort NeList{String} to NeStringList,
     sort List{String} to StringList) .
  protecting QID-LIST .

  vars S P : String .
  var  SL : StringList .
  var  QI : Qid .
  var  QIL : QidList .

  *** qid-list  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - --
  op qid-list : StringList -> QidList .
  eq qid-list(nil) = nil .
  eq qid-list(S SL) = qid(S) qid-list(SL) .

  *** string-list  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  op string-list : QidList -> StringList .
  eq string-list(nil) = nil .
  eq string-list(QI QIL) = string(QI) string-list(QIL) .

  *** prepend  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  op prepend : StringList String -> StringList .
  eq prepend(nil, P) = nil .
  eq prepend(S SL, P) = (P + S) prepend(SL, P) .
endfm

********************************************************************************
